### ISSUE TITLE
[Feature] Handle localStorage in universal react app

### ISSUE THREAD

**Issue by artemidas** [remarkablemark/universal-react-tutorial#1]

**Comment by remarkablemark** [comment]
This would be a very nice feature but unfortunately local storage can only be accessed on the _client_ (and not on the server).

If you have data that needs to be accessed on both the server and client, there are 2 solutions that I can think of:
1. cookies
2. query string parameters

And **cookies** being the superior solution in my opinion. What do you think @Artemidas?

**Comment by artemidas** [comment]
You are right @remarkablemark.
And is it good practice to store JWT in cookies for future secure api calls and user auth?
Also for storing Redux's store, if it's needed of-course.

**Comment by remarkablemark** [comment]
It should be fine as long as the cookie secure. Just be careful of [CSRF](https://en.wikipedia.org/wiki/Cross-site_request_forgery) vulnerabilities.

**Comment by artemidas** [comment]
Okey, I've read about it. I should protect the React app from CSRF. Thanks!

**Comment by remarkablemark** [comment]
No problem, I'll be closing the issue then!
